#foreground #ddc7a1
foreground white
background #282828
#background_opacity 0.9
#background_blur 32

window_margin_width 4
cursor_shape block
#cursor_trail 1
#shell_integration no-cursor
map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0

# font stuff
font_family 0xProtoNerdFontMono
font_size 12.0
bold_font auto
italic_font auto
bold_italic_font auto
