general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    monitor =
    color = rgba(31, 31, 40, 1)
}

label {
    monitor =
    text = session locked — $USER
    color = rgba(220, 215, 186, 0.5)
    font_size = 16
    font_family = RobotoMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 280, 44
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.2
    outer_color = rgba(126, 156, 216, 0.4)
    inner_color = rgba(42, 42, 55, 0.9)
    font_color = rgba(220, 215, 186, 0.9)
    fade_on_empty = false
    font_family = RobotoMono Nerd Font
    fail_color = rgba(228, 104, 118, 0.9)
    fail_text = <i>$FAIL</i>
    capslock_color = rgba(192, 163, 110, 0.9)
    position = 0, 20
    halign = center
    valign = center
}
