general {
    lock_cmd = none
    before_sleep_cmd = none
    after_sleep_cmd = none
    ignore_dbus_inhibit = false
}

listener {
    timeout = 900  # seconds (15 minutes)
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
